version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    env_file: .env
    volumes:
      - .:/frontend